version: '3.8'

services:
  expo:
    build:
    context: ./client
    dockerfile: Dockerfile
    ports:
      - "19000:19000"
      
    volumes:
      - ./client:/app
    command: npm start

  # api:
  #   image: node:18
  #   working_dir: /app
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "5000:5000"
  #   command: npm start
